on: pull_request
name: Run tests
jobs:
  run_tests:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [10,11,12,13]
      fail-fast: true
    steps:
      - uses: actions/checkout@v1
      - name: check cache
        id: npm-cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node${{ hashFiles('**/yarn.lock') }}
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install Deps if no cache
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: yarn
      - name: Execute tests
        run: yarn ci-test