on: pull_request
name: Run tests
jobs:
  run_tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: check cache
        id: npm-cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node${{ hashFiles('**/yarn.lock') }}
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.18.0
      - name: Install Deps if no cache
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: yarn install --ignore-engines
      - name: Run Linter
        run: yarn lint
      - name: Execute tests
        run: yarn ci-test
